---
title: 'DSO 522: Final Project - Walmart Sales Prediction'
author: 'Group 8'
output:
  pdf_document: default
  word_document: default
header-includes: \usepackage{color}
editor_options: 
  chunk_output_type: console
---

- Prepare Data

Data Cleaning
```{r}
# Read Clean
data = read.csv("Walmart.csv", header = T)
head(data,3)

# Create Time Target (143 weeks, 45 stores in total)
data$week = rep(1:143,45)

# Data Weekly Average Calculation
data_clean = aggregate(data, list(DateAgg = data$Date), mean)
index.ord = order(data_clean$week)
data_clean = data_clean[index.ord,]
data_clean = data_clean[,c(1,4,5,6,7,8,9)]
# New Dataset: Only Include DataAgg, Weekly_Sales, Holiday_Flag, Temperature, Fuel_Price, CPI, Unemployment
head(data_clean,5)
```

Transforming to Time Series
```{r}
WeeklySales.ts = ts(data_clean$Weekly_Sales, start = c(2010,6), frequency = 52)
plot(WeeklySales.ts)
```


- Naive & Seasonal Forecast

- Exponential Smoothing & Moving Average/Trailing

- ARIMA/ Seasonal ARIMA

- Multiple Linear Regression

step1: Construct other factors
```{r}
HolidayFlag.ts = ts(data_clean$Holiday_Flag, start = c(2010,6), frequency = 52)
Temp.ts = ts(data_clean$Temperature, start = c(2010,6), frequency = 52)
plot(Temp.ts)
Fuel.ts = ts(data_clean$Fuel_Price, start = c(2010,6), frequency = 52)
plot(Fuel.ts)
Cpi.ts = ts(data_clean$CPI, start = c(2010,6), frequency = 52)
plot(Cpi.ts)
Rate.ts = ts(data_clean$Unemployment, start = c(2010,6), frequency = 52)
plot(Rate.ts)
```

step2: Find Relationships
```{r}
library(ggplot2)
# WeeklySales.ts = ts(log(data_clean$Weekly_Sales), start = c(2010,6), frequency = 52)
qplot(HolidayFlag.ts,WeeklySales.ts)
qplot(Temp.ts,WeeklySales.ts)
qplot(Fuel.ts,WeeklySales.ts)
qplot(Cpi.ts,WeeklySales.ts)
qplot(Rate.ts,WeeklySales.ts)
```

step3: Test CCF
```{r}
library(astsa)
Ccf(Temp.ts, WeeklySales.ts, 50)
# 20/42 lag should be significant
Ccf(Fuel.ts, WeeklySales.ts, 50)
# 31 lag should be significant
Ccf(Cpi.ts, WeeklySales.ts, 50)
Ccf(Rate.ts, WeeklySales.ts, 50)
```

step4: 
Single Model:
```{r}
library(forecast)
# test temperature
newdata1= ts.intersect(WeeklySales.ts, leadR20=lag(Temp.ts,-20), leadR42=lag(Temp.ts,-42))
# model 1
m1 = tslm(WeeklySales.ts~leadR20, data = newdata1)
summary(m1)
accuracy(m1)
# model 2
m2 = tslm(WeeklySales.ts~leadR42, data = newdata1)
summary(m2)
accuracy(m2)
# Obviously, both two models do not have good prediction power. However, first one is a little bit better.
```
```{r}
# test temperature
newdata2= ts.intersect(WeeklySales.ts, leadR31=lag(Fuel.ts,-31),Fuel.ts)
# model 3
m3 = tslm(WeeklySales.ts~leadR31, data = newdata2)
summary(m3)
accuracy(m3)
# model 4
m4 = tslm(WeeklySales.ts~Fuel.ts, data = newdata2)
summary(m4)
accuracy(m4)
# Obviously, both two models do not have good prediction power. However, first one is a little bit better.
```
Hybrid Model:
```{r}
# Build Final Model
newdata= ts.intersect(WeeklySales.ts, fuel=lag(Fuel.ts,-31), temp=lag(Temp.ts,-20), holiday = HolidayFlag.ts, cpi = Cpi.ts, rate = Rate.ts)
# model 5
m5 = tslm(WeeklySales.ts~ temp+fuel, data = newdata)
summary(m5)
accuracy(m5)
# model 6
m6 = tslm(WeeklySales.ts~ temp+fuel+holiday, data = newdata)
summary(m6)
accuracy(m6)
# model 7 
m7 = tslm(WeeklySales.ts~ temp+fuel+holiday+cpi, data = newdata)
summary(m7)
accuracy(m7)
# model 8
m8 = tslm(WeeklySales.ts~ temp+fuel+holiday+cpi+rate, data = newdata)
summary(m8)
accuracy(m8)
# All models are horrible, m7 should be the best.
```
Plot:
```{r}
autoplot(m7$fitted.values) + autolayer(WeeklySales.ts)
```

Conclusion For Regression: Trash Variables and Trash Models!
